import { CORE_OBJECT_REACTION_EMOJIS } from "@/features/activity/components/conversation-workspace/emoji-picker-panel/reaction-emojis/core-object-reaction-emojis";
import { reactionEmoji } from "@/features/activity/components/conversation-workspace/emoji-picker-panel/reaction-emojis/emoji-factory";

export const COMPACT_REACTION_GROUPS = [
  {
    title: "Smileys & emotion",
    emojis: [
      reactionEmoji("😀", "Grinning face", ["happy", "smile"]),
      reactionEmoji("😃", "Big smile", ["happy", "smile"]),
      reactionEmoji("😄", "Smiling eyes", ["happy", "smile"]),
      reactionEmoji("😁", "Beaming face", ["happy", "smile"]),
      reactionEmoji("😆", "Laughing face", ["laugh", "funny"]),
      reactionEmoji("😇", "Halo face", ["kind", "good"]),
      reactionEmoji("😉", "Winking face", ["wink", "playful"]),
      reactionEmoji("😋", "Yum face", ["food", "nice"]),
      reactionEmoji("😛", "Tongue face", ["silly", "playful"]),
      reactionEmoji("😜", "Winking tongue", ["silly", "joke"]),
      reactionEmoji("🤪", "Zany face", ["silly", "wild"]),
      reactionEmoji("😝", "Squinting tongue", ["silly", "joke"]),
      reactionEmoji("🫠", "Melting face", ["awkward", "overwhelmed"]),
      reactionEmoji("🤭", "Hand over mouth", ["oops", "laugh"]),
      reactionEmoji("🫡", "Saluting face", ["respect", "done"]),
      reactionEmoji("🤫", "Shushing face", ["quiet", "secret"]),
      reactionEmoji("😐", "Neutral face", ["neutral", "ok"]),
      reactionEmoji("😑", "Expressionless face", ["blank", "done"]),
      reactionEmoji("😶", "Face without mouth", ["silent", "speechless"]),
      reactionEmoji("🫥", "Dotted line face", ["invisible", "awkward"]),
      reactionEmoji("😏", "Smirking face", ["smirk", "playful"]),
      reactionEmoji("😒", "Unamused face", ["annoyed", "bored"]),
      reactionEmoji("🙄", "Rolling eyes", ["annoyed", "sarcastic"]),
      reactionEmoji("😳", "Flushed face", ["embarrassed", "wow"]),
      reactionEmoji("🥺", "Pleading face", ["please", "soft"]),
      reactionEmoji("🥲", "Smiling tear", ["touched", "sad happy"]),
      reactionEmoji("🥹", "Holding back tears", ["touched", "sweet"]),
      reactionEmoji("😭", "Loudly crying face", ["cry", "emotional"]),
      reactionEmoji("😢", "Crying face", ["sad", "sorry"]),
      reactionEmoji("😞", "Disappointed face", ["sad", "sorry"]),
      reactionEmoji("😔", "Pensive face", ["sad", "thinking"]),
      reactionEmoji("😟", "Worried face", ["worry", "concern"]),
      reactionEmoji("😕", "Confused face", ["confused", "unsure"]),
      reactionEmoji("🙁", "Slight frown", ["sad", "frown"]),
      reactionEmoji("☹️", "Frowning face", ["sad", "frown"]),
      reactionEmoji("😣", "Persevering face", ["struggle", "effort"]),
      reactionEmoji("😖", "Confounded face", ["frustrated", "confused"]),
      reactionEmoji("😫", "Tired face", ["tired", "exhausted"]),
      reactionEmoji("😩", "Weary face", ["tired", "please"]),
      reactionEmoji("🥱", "Yawning face", ["tired", "sleepy"]),
      reactionEmoji("😴", "Sleeping face", ["tired", "sleep"]),
      reactionEmoji("🤤", "Drooling face", ["want", "food"]),
      reactionEmoji("🥶", "Cold face", ["cold", "freeze"]),
      reactionEmoji("🥵", "Hot face", ["hot", "intense"]),
      reactionEmoji("🤢", "Nauseated face", ["sick", "gross"]),
      reactionEmoji("🤮", "Vomiting face", ["sick", "gross"]),
      reactionEmoji("🤧", "Sneezing face", ["sick", "cold"]),
      reactionEmoji("😷", "Medical mask face", ["sick", "mask"]),
      reactionEmoji("🤒", "Thermometer face", ["sick", "fever"]),
      reactionEmoji("🤕", "Bandaged face", ["hurt", "injured"]),
      reactionEmoji("🤑", "Money face", ["money", "rich"]),
      reactionEmoji("🤠", "Cowboy face", ["fun", "hat"]),
      reactionEmoji("🥸", "Disguised face", ["secret", "glasses"]),
      reactionEmoji("🤓", "Nerd face", ["smart", "study"]),
      reactionEmoji("🧐", "Monocle face", ["inspect", "curious"]),
      reactionEmoji("😎", "Sunglasses face", ["cool", "confident"]),
      reactionEmoji("🥳", "Partying face", ["party", "celebrate"]),
      reactionEmoji("🤯", "Exploding head", ["mind blown", "wow"]),
    ],
  },
  {
    title: "People & body",
    emojis: [
      reactionEmoji("👍", "Thumbs up", ["yes", "agree", "ok", "approve"]),
      reactionEmoji("👎", "Thumbs down", ["no", "disagree"]),
      reactionEmoji("👏", "Clapping hands", ["applause", "nice"]),
      reactionEmoji("🙌", "Raised hands", ["yay", "celebrate"]),
      reactionEmoji("🙏", "Folded hands", ["please", "thanks"]),
      reactionEmoji("🤝", "Handshake", ["deal", "support", "agree"]),
      reactionEmoji("💪", "Flexed biceps", ["strong", "power"]),
      reactionEmoji("🫶", "Heart hands", ["care", "support"]),
      reactionEmoji("👌", "OK hand", ["ok", "perfect"]),
      reactionEmoji("🤌", "Pinched fingers", ["chef kiss", "perfect"]),
      reactionEmoji("👋", "Waving hand", ["hello", "bye"]),
      reactionEmoji("🤚", "Raised back hand", ["stop", "hand"]),
      reactionEmoji("✋", "Raised hand", ["stop", "hand"]),
      reactionEmoji("🖐️", "Hand with fingers splayed", ["hand", "five"]),
      reactionEmoji("🖖", "Vulcan salute", ["hello", "salute"]),
      reactionEmoji("✌️", "Victory hand", ["peace", "two"]),
      reactionEmoji("🤞", "Crossed fingers", ["hope", "luck"]),
      reactionEmoji("🫰", "Finger heart", ["love", "care"]),
      reactionEmoji("🤟", "Love-you gesture", ["love", "sign"]),
      reactionEmoji("🤘", "Rock hand", ["rock", "music"]),
      reactionEmoji("👈", "Point left", ["point", "left"]),
      reactionEmoji("👉", "Point right", ["point", "right"]),
      reactionEmoji("👆", "Point up", ["point", "up"]),
      reactionEmoji("👇", "Point down", ["point", "down"]),
      reactionEmoji("☝️", "Index up", ["point", "up"]),
      reactionEmoji("🫵", "Pointing at viewer", ["you", "point"]),
      reactionEmoji("✊", "Raised fist", ["power", "solidarity"]),
      reactionEmoji("👊", "Oncoming fist", ["bump", "power"]),
      reactionEmoji("🤛", "Left fist bump", ["bump", "fist"]),
      reactionEmoji("🤜", "Right fist bump", ["bump", "fist"]),
      reactionEmoji("🫳", "Palm down hand", ["hand", "drop"]),
      reactionEmoji("🫴", "Palm up hand", ["hand", "offer"]),
      reactionEmoji("🤲", "Palms up together", ["offer", "please"]),
      reactionEmoji("👐", "Open hands", ["open", "hug"]),
      reactionEmoji("💅", "Nail polish", ["style", "sass"]),
      reactionEmoji("🧠", "Brain", ["smart", "think"]),
      reactionEmoji("👀", "Eyes", ["watching", "looking"]),
      reactionEmoji("👂", "Ear", ["listen", "hear"]),
      reactionEmoji("🗣️", "Speaking head", ["talk", "speak"]),
      reactionEmoji("👤", "Bust silhouette", ["person", "user"]),
      reactionEmoji("👥", "Busts silhouettes", ["people", "group"]),
      reactionEmoji("🧑‍💻", "Technologist", ["work", "computer"]),
      reactionEmoji("🧑‍🎓", "Student", ["study", "learn"]),
      reactionEmoji("🧑‍🍳", "Cook", ["food", "cook"]),
      reactionEmoji("🫂", "People hugging", ["hug", "support"]),
    ],
  },
  {
    title: "Hearts & symbols",
    emojis: [
      reactionEmoji("❤️", "Red heart", ["love", "care", "warm"]),
      reactionEmoji("🧡", "Orange heart", ["love", "warm"]),
      reactionEmoji("💛", "Yellow heart", ["love", "happy"]),
      reactionEmoji("💚", "Green heart", ["love", "support"]),
      reactionEmoji("💙", "Blue heart", ["love", "calm"]),
      reactionEmoji("💜", "Purple heart", ["love", "care"]),
      reactionEmoji("🖤", "Black heart", ["love", "dark"]),
      reactionEmoji("🤍", "White heart", ["love", "pure"]),
      reactionEmoji("🤎", "Brown heart", ["love", "warm"]),
      reactionEmoji("💔", "Broken heart", ["sad", "hurt"]),
      reactionEmoji("❣️", "Heart exclamation", ["love", "emphasis"]),
      reactionEmoji("💕", "Two hearts", ["love", "sweet"]),
      reactionEmoji("💞", "Revolving hearts", ["love", "cute"]),
      reactionEmoji("💓", "Beating heart", ["love", "excited"]),
      reactionEmoji("💗", "Growing heart", ["love", "care"]),
      reactionEmoji("💖", "Particleling heart", ["love", "particlele"]),
      reactionEmoji("💘", "Heart with arrow", ["love", "crush"]),
      reactionEmoji("💝", "Heart with ribbon", ["gift", "love"]),
      reactionEmoji("💟", "Heart decoration", ["love", "symbol"]),
      reactionEmoji("✅", "Check mark", ["done", "yes", "complete"]),
      reactionEmoji("☑️", "Checked box", ["done", "check"]),
      reactionEmoji("✔️", "Heavy check mark", ["done", "yes"]),
      reactionEmoji("❌", "Cross mark", ["no", "wrong", "cancel"]),
      reactionEmoji("❎", "Cross box", ["no", "wrong"]),
      reactionEmoji("⚠️", "Warning", ["careful", "alert"]),
      reactionEmoji("🚫", "Prohibited", ["no", "blocked"]),
      reactionEmoji("💯", "Hundred points", ["perfect", "true"]),
      reactionEmoji("💥", "Collision", ["boom", "impact"]),
      reactionEmoji("💫", "Dizzy", ["stars", "wow"]),
      reactionEmoji("✨", "Particleles", ["magic", "nice", "clean"]),
      reactionEmoji("⭐", "Star", ["star", "favorite"]),
      reactionEmoji("🌟", "Glowing star", ["star", "shine"]),
      reactionEmoji("⚡", "Lightning", ["fast", "energy"]),
      reactionEmoji("🔥", "Fire", ["hot", "great", "strong"]),
      reactionEmoji("🎯", "Bullseye", ["target", "exact"]),
      reactionEmoji("🔔", "Bell", ["notify", "reminder"]),
      reactionEmoji("💬", "Speech bubble", ["chat", "message"]),
      reactionEmoji("💭", "Thought bubble", ["think", "idea"]),
      reactionEmoji("🗯️", "Anger bubble", ["shout", "talk"]),
      reactionEmoji("💤", "Zzz", ["sleep", "tired"]),
    ],
  },
  {
    title: "Animals & nature",
    emojis: [
      reactionEmoji("🐶", "Dog face", ["dog", "pet"]),
      reactionEmoji("🐱", "Cat face", ["cat", "pet"]),
      reactionEmoji("🐭", "Mouse face", ["mouse", "cute"]),
      reactionEmoji("🐹", "Hamster face", ["hamster", "cute"]),
      reactionEmoji("🐰", "Rabbit face", ["rabbit", "cute"]),
      reactionEmoji("🦊", "Fox face", ["fox", "animal"]),
      reactionEmoji("🐻", "Bear", ["bear", "animal"]),
      reactionEmoji("🐼", "Panda", ["panda", "cute"]),
      reactionEmoji("🐨", "Koala", ["koala", "cute"]),
      reactionEmoji("🐯", "Tiger", ["tiger", "animal"]),
      reactionEmoji("🦁", "Lion", ["lion", "animal"]),
      reactionEmoji("🐮", "Cow", ["cow", "animal"]),
      reactionEmoji("🐷", "Pig", ["pig", "animal"]),
      reactionEmoji("🐸", "Frog", ["frog", "animal"]),
      reactionEmoji("🐵", "Monkey", ["monkey", "animal"]),
      reactionEmoji("🐧", "Penguin", ["penguin", "animal"]),
      reactionEmoji("🐦", "Bird", ["bird", "animal"]),
      reactionEmoji("🦆", "Duck", ["duck", "animal"]),
      reactionEmoji("🦉", "Owl", ["owl", "animal"]),
      reactionEmoji("🐢", "Turtle", ["turtle", "animal"]),
      reactionEmoji("🌱", "Seedling", ["plant", "grow"]),
      reactionEmoji("🌿", "Herb", ["plant", "nature"]),
      reactionEmoji("🍀", "Four leaf clover", ["luck", "green"]),
      reactionEmoji("🌵", "Cactus", ["plant", "desert"]),
      reactionEmoji("🌴", "Palm tree", ["tree", "travel"]),
      reactionEmoji("🌳", "Deciduous tree", ["tree", "nature"]),
      reactionEmoji("🌲", "Evergreen tree", ["tree", "nature"]),
      reactionEmoji("🌺", "Hibiscus", ["flower", "nature"]),
      reactionEmoji("🌸", "Cherry blossom", ["flower", "spring"]),
      reactionEmoji("🌼", "Blossom", ["flower", "nature"]),
      reactionEmoji("🌻", "Sunflower", ["flower", "sun"]),
      reactionEmoji("🌹", "Rose", ["flower", "love"]),
      reactionEmoji("🌷", "Tulip", ["flower", "spring"]),
      reactionEmoji("☀️", "Sun", ["sun", "bright"]),
      reactionEmoji("🌙", "Moon", ["night", "calm"]),
      reactionEmoji("🌧️", "Rain cloud", ["rain", "weather"]),
      reactionEmoji("⛈️", "Storm cloud", ["storm", "weather"]),
      reactionEmoji("❄️", "Snowflake", ["snow", "cold"]),
      reactionEmoji("☁️", "Cloud", ["cloud", "weather"]),
      reactionEmoji("🌊", "Wave", ["water", "sea"]),
      reactionEmoji("🔥", "Fire", ["hot", "great", "strong"]),
      reactionEmoji("🌈", "Rainbow", ["color", "nice"]),
      reactionEmoji("⭐", "Star", ["star", "favorite"]),
      reactionEmoji("⚡", "Lightning", ["fast", "energy"]),
    ],
  },
  {
    title: "Food & activity",
    emojis: [
      reactionEmoji("🍕", "Pizza", ["food", "slice"]),
      reactionEmoji("🍔", "Burger", ["food", "meal"]),
      reactionEmoji("🍟", "Fries", ["food", "snack"]),
      reactionEmoji("🌮", "Taco", ["food", "meal"]),
      reactionEmoji("🍣", "Sushi", ["food", "meal"]),
      reactionEmoji("🍜", "Noodles", ["food", "meal"]),
      reactionEmoji("🍝", "Spaghetti", ["food", "meal"]),
      reactionEmoji("🍗", "Poultry leg", ["food", "meal"]),
      reactionEmoji("🥗", "Green salad", ["food", "healthy"]),
      reactionEmoji("🍓", "Strawberry", ["fruit", "sweet"]),
      reactionEmoji("🍌", "Banana", ["fruit", "snack"]),
      reactionEmoji("🍎", "Apple", ["fruit", "snack"]),
      reactionEmoji("🥑", "Avocado", ["food", "healthy"]),
      reactionEmoji("🍩", "Doughnut", ["sweet", "food"]),
      reactionEmoji("🍪", "Cookie", ["sweet", "food"]),
      reactionEmoji("🍰", "Cake", ["sweet", "celebrate"]),
      reactionEmoji("🧁", "Cupcake", ["sweet", "celebrate"]),
      reactionEmoji("🍫", "Chocolate", ["sweet", "food"]),
      reactionEmoji("🍿", "Popcorn", ["movie", "snack"]),
      reactionEmoji("☕", "Coffee", ["drink", "cafe"]),
      reactionEmoji("🍵", "Tea", ["drink", "calm"]),
      reactionEmoji("🧋", "Bubble tea", ["drink", "tea"]),
      reactionEmoji("🥤", "Cup with straw", ["drink", "soda"]),
      reactionEmoji("🍻", "Beers", ["drink", "cheers"]),
      reactionEmoji("🥂", "Clinking glasses", ["cheers", "celebrate"]),
      reactionEmoji("🏀", "Basketball", ["sport", "game"]),
      reactionEmoji("⚽", "Football", ["sport", "game"]),
      reactionEmoji("🏈", "American football", ["sport", "game"]),
      reactionEmoji("⚾", "Baseball", ["sport", "game"]),
      reactionEmoji("🎾", "Tennis", ["sport", "game"]),
      reactionEmoji("🏐", "Volleyball", ["sport", "game"]),
      reactionEmoji("🏓", "Table tennis", ["sport", "game"]),
      reactionEmoji("🎮", "Video game", ["game", "play"]),
      reactionEmoji("🎲", "Game die", ["game", "play"]),
      reactionEmoji("♟️", "Chess pawn", ["game", "chess"]),
      reactionEmoji("🎧", "Headphones", ["music", "listen"]),
      reactionEmoji("🎤", "Microphone", ["music", "sing"]),
      reactionEmoji("🎵", "Musical note", ["music", "song"]),
      reactionEmoji("🎬", "Clapper board", ["movie", "film"]),
      ...CORE_OBJECT_REACTION_EMOJIS,
      reactionEmoji("🎁", "Gift", ["present", "celebrate"]),
      reactionEmoji("🎈", "Balloon", ["party", "celebrate"]),
      reactionEmoji("🎊", "Confetti ball", ["celebrate", "party"]),
      reactionEmoji("🎉", "Party popper", ["celebrate", "congrats"]),
      reactionEmoji("🚀", "Rocket", ["launch", "fast", "go"]),
      reactionEmoji("✈️", "Airplane", ["travel", "flight"]),
      reactionEmoji("🚗", "Car", ["travel", "drive"]),
      reactionEmoji("🏠", "House", ["home", "place"]),
      reactionEmoji("🏫", "School", ["study", "campus"]),
    ],
  },
] as const;
