import { CORE_OBJECT_REACTION_EMOJIS } from "@/features/activity/components/conversation-workspace/emoji-picker-panel/reaction-emojis/core-object-reaction-emojis";
import { reactionEmoji } from "@/features/activity/components/conversation-workspace/emoji-picker-panel/reaction-emojis/emoji-factory";

export const SUGGESTED_REACTION_EMOJIS = [
  reactionEmoji("👍", "Thumbs up", ["yes", "agree", "ok", "approve"]),
  reactionEmoji("❤️", "Red heart", ["love", "care", "warm"]),
  reactionEmoji("😂", "Face with tears of joy", ["laugh", "funny"]),
  reactionEmoji("🔥", "Fire", ["hot", "great", "strong"]),
  reactionEmoji("🎉", "Party popper", ["celebrate", "congrats"]),
  reactionEmoji("👏", "Clapping hands", ["applause", "nice"]),
  reactionEmoji("✨", "Sparkles", ["magic", "nice", "clean"]),
  reactionEmoji("🤝", "Handshake", ["deal", "support", "agree"]),
  reactionEmoji("😍", "Heart eyes", ["love", "excited"]),
  reactionEmoji("😊", "Smiling face", ["happy", "kind"]),
  reactionEmoji("🙏", "Folded hands", ["please", "thanks"]),
  reactionEmoji("🙌", "Raised hands", ["yay", "celebrate"]),
  reactionEmoji("👀", "Eyes", ["watching", "looking"]),
  reactionEmoji("💯", "Hundred points", ["perfect", "true"]),
  reactionEmoji("🚀", "Rocket", ["launch", "fast", "go"]),
  reactionEmoji("😅", "Grinning sweat", ["relief", "nervous laugh"]),
  reactionEmoji("🤔", "Thinking face", ["think", "curious"]),
  reactionEmoji("😎", "Sunglasses face", ["cool", "confident"]),
  reactionEmoji("🥳", "Partying face", ["party", "celebrate"]),
  reactionEmoji("😭", "Loudly crying face", ["cry", "emotional"]),
  reactionEmoji("🥹", "Holding back tears", ["touched", "sweet"]),
  reactionEmoji("😮", "Surprised face", ["wow", "shock"]),
  reactionEmoji("😢", "Crying face", ["sad", "sorry"]),
  reactionEmoji("😡", "Angry face", ["mad", "frustrated"]),
  reactionEmoji("🤯", "Exploding head", ["mind blown", "wow"]),
  reactionEmoji("💪", "Flexed biceps", ["strong", "power"]),
  reactionEmoji("👌", "OK hand", ["ok", "perfect"]),
  reactionEmoji("🫶", "Heart hands", ["care", "support"]),
  reactionEmoji("🤗", "Hugging face", ["hug", "support"]),
  reactionEmoji("😬", "Grimacing face", ["awkward", "tense"]),
  reactionEmoji("🙃", "Upside-down face", ["silly", "awkward"]),
  reactionEmoji("😴", "Sleeping face", ["tired", "sleep"]),
  reactionEmoji("🤩", "Star-struck", ["excited", "amazed"]),
  reactionEmoji("😌", "Relieved face", ["calm", "good"]),
  reactionEmoji("😤", "Face with steam", ["determined", "annoyed"]),
  reactionEmoji("😱", "Screaming face", ["scared", "shock"]),
  reactionEmoji("✅", "Check mark", ["done", "yes", "complete"]),
  reactionEmoji("❌", "Cross mark", ["no", "wrong", "cancel"]),
  reactionEmoji("⚠️", "Warning", ["careful", "alert"]),
  reactionEmoji("💔", "Broken heart", ["sad", "hurt"]),
  reactionEmoji("💜", "Purple heart", ["love", "care"]),
  reactionEmoji("🥰", "Smiling face with hearts", ["love", "sweet"]),
  reactionEmoji("🫠", "Melting face", ["awkward", "overwhelmed"]),
  reactionEmoji("🙄", "Rolling eyes", ["annoyed", "sarcastic"]),
  reactionEmoji("😏", "Smirking face", ["smirk", "playful"]),
  reactionEmoji("😜", "Winking tongue", ["silly", "joke"]),
  reactionEmoji("🤪", "Zany face", ["silly", "wild"]),
  reactionEmoji("😋", "Yum face", ["food", "nice"]),
  reactionEmoji("🥱", "Yawning face", ["tired", "sleepy"]),
  reactionEmoji("😇", "Halo face", ["kind", "good"]),
  reactionEmoji("😈", "Smiling face with horns", ["mischief", "playful"]),
  reactionEmoji("👋", "Waving hand", ["hello", "bye"]),
  reactionEmoji("✌️", "Victory hand", ["peace", "two"]),
  reactionEmoji("🫡", "Saluting face", ["respect", "done"]),
  reactionEmoji("🤣", "Rolling laughing face", ["laugh", "funny", "lol"]),
  reactionEmoji("😄", "Smiling eyes", ["happy", "smile"]),
  reactionEmoji("😆", "Laughing face", ["laugh", "funny"]),
  reactionEmoji("😳", "Flushed face", ["embarrassed", "wow"]),
  reactionEmoji("😶", "Face without mouth", ["silent", "speechless"]),
  reactionEmoji("😐", "Neutral face", ["neutral", "ok"]),
  reactionEmoji("😑", "Expressionless face", ["blank", "done"]),
  reactionEmoji("😒", "Unamused face", ["annoyed", "bored"]),
  reactionEmoji("🤭", "Hand over mouth", ["oops", "laugh"]),
  reactionEmoji("🫢", "Eyes open hand over mouth", ["oops", "shock"]),
  reactionEmoji("🫣", "Peeking face", ["shy", "watching"]),
  reactionEmoji("😵", "Dizzy face", ["stunned", "overwhelmed"]),
  reactionEmoji("😵‍💫", "Spiral eyes face", ["dizzy", "confused"]),
  reactionEmoji("😞", "Disappointed face", ["sad", "sorry"]),
  reactionEmoji("😔", "Pensive face", ["sad", "thinking"]),
  reactionEmoji("😕", "Confused face", ["confused", "unsure"]),
  reactionEmoji("🙂", "Slight smile", ["smile", "ok"]),
  reactionEmoji("😀", "Grinning face", ["happy", "smile"]),
  reactionEmoji("😃", "Big smile", ["happy", "smile"]),
  reactionEmoji("😛", "Tongue face", ["silly", "playful"]),
  reactionEmoji("😝", "Squinting tongue", ["silly", "joke"]),
  reactionEmoji("🤤", "Drooling face", ["want", "food"]),
  reactionEmoji("😮‍💨", "Exhaling face", ["relief", "tired"]),
  reactionEmoji("🤌", "Pinched fingers", ["chef kiss", "perfect"]),
  reactionEmoji("🤞", "Crossed fingers", ["hope", "luck"]),
  reactionEmoji("👊", "Oncoming fist", ["bump", "power"]),
  reactionEmoji("✊", "Raised fist", ["power", "solidarity"]),
  reactionEmoji("🤘", "Rock hand", ["rock", "music"]),
  reactionEmoji("🫰", "Finger heart", ["love", "care"]),
  reactionEmoji("🫂", "People hugging", ["hug", "support"]),
  reactionEmoji("💥", "Collision", ["boom", "impact"]),
  reactionEmoji("⭐", "Star", ["star", "favorite"]),
  reactionEmoji("🌟", "Glowing star", ["star", "shine"]),
  reactionEmoji("⚡", "Lightning", ["fast", "energy"]),
  reactionEmoji("🌈", "Rainbow", ["color", "nice"]),
  reactionEmoji("☀️", "Sun", ["sun", "bright"]),
  reactionEmoji("🍕", "Pizza", ["food", "slice"]),
  reactionEmoji("☕", "Coffee", ["drink", "cafe"]),
  reactionEmoji("🎮", "Video game", ["game", "play"]),
  reactionEmoji("🎧", "Headphones", ["music", "listen"]),
  ...CORE_OBJECT_REACTION_EMOJIS,
  reactionEmoji("🎯", "Bullseye", ["target", "exact"]),
  reactionEmoji("🔔", "Bell", ["notify", "reminder"]),
  reactionEmoji("📝", "Memo", ["note", "write"]),
  reactionEmoji("💬", "Speech bubble", ["chat", "message"]),
] as const;
