import type { User } from "@/shared/schemas";

export const PROFILE_PAGE_SKELETON_NAME = "profile.page";

export const profilePageSkeletonFixture = {
  id: "profile-skeleton-fixture",
  email: "maya.rivera@example.com",
  name: "Maya Rivera",
  avatar: null,
  bio: "I like plans that leave room for a real conversation: a clear place to meet, a shared thing to do, and enough breathing room for everyone to settle in.",
  authProvider: "EMAIL",
  googleId: null,
  emailVerified: true,
  createdAt: "2026-01-10T10:00:00.000Z",
  updatedAt: "2026-05-01T10:00:00.000Z",
  age: 24,
  gender: "NON_BINARY",
  city: "Bristol",
  locationLat: null,
  locationLng: null,
  personalityType: "ENFP",
  oceanO: 84,
  oceanC: 62,
  oceanE: 72,
  oceanA: 78,
  oceanN: 34,
  searchStatus: "IDLE",
  onlineStatus: "ONLINE",
  trustScore: 88,
  profileComplete: true,
  interests: [
    {
      id: "interest-film",
      name: "Indie film",
      slug: "indie-film",
      description: "Small screenings, thoughtful stories, and post-film chats.",
      icon: null,
      color: null,
      sortOrder: 1,
      isActive: true,
      parentId: null,
      aliases: ["cinema", "film clubs"],
    },
    {
      id: "interest-climbing",
      name: "Bouldering",
      slug: "bouldering",
      description: "Low-pressure climbing sessions and coffee after.",
      icon: null,
      color: null,
      sortOrder: 2,
      isActive: true,
      parentId: null,
      aliases: ["climbing"],
    },
    {
      id: "interest-design",
      name: "Design critique",
      slug: "design-critique",
      description: "Talking through products, posters, and visual systems.",
      icon: null,
      color: null,
      sortOrder: 3,
      isActive: true,
      parentId: null,
      aliases: ["ux", "visual design"],
    },
    {
      id: "interest-food",
      name: "Street food",
      slug: "street-food",
      description: "Casual food walks and trying new local spots.",
      icon: null,
      color: null,
      sortOrder: 4,
      isActive: true,
      parentId: null,
      aliases: ["markets"],
    },
  ],
} satisfies User;
