import type { PlanCategory } from "@/shared/schemas";

export const ACTIVITY_SEMANTIC_TERMS: Partial<Record<PlanCategory, string[]>> =
  {
    ARTS: [
      "cinema",
      "craft",
      "crafts",
      "exhibition",
      "exhibitions",
      "film",
      "films",
      "gallery",
      "galleries",
      "movie",
      "movies",
      "museum",
      "museums",
      "painting",
      "photography",
      "pottery",
      "screening",
      "theater",
      "theatre",
    ],
    FOOD: [
      "baking",
      "breakfast",
      "cafe",
      "cafes",
      "cook",
      "cooking",
      "dinner",
      "lunch",
      "market",
      "markets",
      "restaurant",
      "restaurants",
      "tasting",
    ],
    GAMING: [
      "arcade",
      "arcades",
      "board game",
      "board games",
      "card games",
      "cards",
      "chess",
      "dnd",
      "esports",
      "tabletop",
      "tabletop games",
      "video game",
      "video games",
    ],
    LEARNING: [
      "book club",
      "course",
      "language exchange",
      "practice",
      "reading",
      "study group",
      "studying",
      "workshop",
      "workshops",
    ],
    MUSIC: [
      "concert",
      "concerts",
      "festival",
      "gig",
      "gigs",
      "jam",
      "jams",
      "karaoke",
      "live music",
      "open mic",
    ],
    OUTDOORS: [
      "bike",
      "biking",
      "camping",
      "cycling",
      "fresh air",
      "hike",
      "hikes",
      "hiking",
      "park",
      "parks",
      "trail",
      "trails",
      "walk",
      "walking",
    ],
    SOCIAL: [
      "brunch",
      "coffee",
      "coffee chat",
      "drinks",
      "hangout",
      "meetup",
      "meetups",
      "networking",
      "party",
      "pub",
      "pub quiz",
      "social",
    ],
    SPORTS: [
      "badminton",
      "basketball",
      "basketball game",
      "bouldering",
      "climbing",
      "football",
      "football game",
      "gym",
      "jogging",
      "padel",
      "run",
      "running",
      "skating",
      "soccer",
      "soccer match",
      "swimming",
      "tennis",
      "tennis match",
      "volleyball",
      "workout",
      "workouts",
    ],
    TECH: [
      "ai",
      "code",
      "coding",
      "demo",
      "demos",
      "hackathon",
      "machine learning",
      "product design",
      "programming",
      "robotics",
      "startup",
      "startups",
      "ui",
      "ux",
    ],
    TRAVEL: [
      "city break",
      "day trip",
      "day trips",
      "discovery",
      "exploring",
      "local gems",
      "road trip",
      "route",
      "routes",
      "sightseeing",
    ],
    WELLNESS: [
      "breathwork",
      "habits",
      "meditation",
      "mindfulness",
      "pilates",
      "recovery",
      "sauna",
      "stretch",
      "stretching",
      "yoga",
    ],
  };
