import type { ForgeWizardData } from "./types";

export function createInitialForgeWizardState(): ForgeWizardData {
  return {
    step: 1,
    navDirection: "forward",
    selectedActivity: null,
    planName: "",
    planDescription: "",
    planDate: "",
    planTime: "",
    planLocation: "",
    planLocationLat: null,
    planLocationLng: null,
    locationType: "TBD",
    planCost: "FREE",
    planCostAmount: "",
    planCostDetails: "",
    forgeMode: "AUTO",
    fixedSize: 6,
    groupSizeMode: "RANGE",
    autoMinSize: 4,
    autoMaxSize: 8,
    compatibilityWeight: 70,
    diversityWeight: 50,
    visibility: "FRIENDS_ONLY",
    forgeResult: "IDLE",
    participants: [],
    removedIds: new Set(),
    groupName: "",
    groupDescription: "",
    manualInviteeIds: [],
    coverImage: null,
    avatarImage: null,
    activityId: null,
    groupId: null,
    chatId: null,
    planId: null,
    inviteCopied: false,
    invitesSent: false,
  };
}
