export const DIRECT_LANE_MATCH_SCORE = 8;
export const TAXONOMY_LANE_MATCH_SCORE = 3.5;
export const CONTEXT_LANE_MATCH_SCORE = 2;
export const SUPPORTING_LANE_SCORE_MULTIPLIER = 0.54;
export const SUPPORTING_LANE_MIN_SCORE = 5;
export const SUPPORTING_LANE_RATIO = 0.58;
