import type { LaneRule } from "../types";

export const laneRules: LaneRule[] = [
  {
    contextPatterns: [/media/, /arts?/, /creative/, /design/],
    key: "creative",
    ownPatterns: [
      /photograph/,
      /\bphoto\b/,
      /graphic design/,
      /\bux\b/,
      /\bui\b/,
      /\bdesign\b/,
      /\bart\b/,
      /paint/,
      /draw/,
      /illustrat/,
      /film/,
      /cinema/,
      /theatre/,
      /music/,
      /\bdj\b/,
      /dance/,
      /writing/,
      /craft/,
      /fashion/,
    ],
    taxonomyIds: ["media_arts", "hobbies_creating", "visual_arts"],
  },
  {
    contextPatterns: [/outdoor/, /sport/, /adventure/, /active/],
    key: "outdoors",
    ownPatterns: [
      /\bski(?:ing)?\b/,
      /\bsnowboard(?:ing)?\b/,
      /\bsurf(?:ing)?\b/,
      /climb/,
      /boulder/,
      /kayak/,
      /scuba/,
      /\bhik(?:e|ing)\b/,
      /\brun(?:ning)?\b/,
      /cycling/,
      /\bbike\b/,
      /camp/,
      /trail/,
      /football/,
      /tennis/,
      /basketball/,
      /swim/,
    ],
    taxonomyIds: ["sports_outdoors", "outdoors", "team_sports"],
  },
  {
    contextPatterns: [/gaming/, /entertainment/, /games?/],
    key: "play",
    ownPatterns: [
      /video games?/,
      /board games?/,
      /\bchess\b/,
      /\bgaming\b/,
      /esport/,
      /puzzle/,
      /trivia/,
      /quiz/,
      /cards?/,
      /dnd/,
      /dungeons/,
    ],
    taxonomyIds: ["gaming", "entertainment"],
  },
  {
    contextPatterns: [/business/, /career/, /tech/, /science/],
    key: "builder",
    ownPatterns: [
      /startup/,
      /product management/,
      /product mgmt/,
      /\bproduct\b/,
      /business/,
      /founder/,
      /entrepreneur/,
      /coding/,
      /software/,
      /\bai\b/,
      /machine learning/,
      /robot/,
      /\bdata\b/,
      /finance/,
      /invest/,
    ],
    taxonomyIds: ["business", "careers", "tech_science"],
  },
  {
    contextPatterns: [/food/, /drink/, /hospitality/],
    key: "food",
    ownPatterns: [
      /coffee/,
      /cafe/,
      /food/,
      /restaurant/,
      /baking/,
      /cooking/,
      /tea/,
      /brunch/,
      /beer/,
      /wine/,
      /cocktail/,
      /market/,
    ],
    taxonomyIds: ["food_drink", "service_hospitality"],
  },
  {
    contextPatterns: [/education/, /learning/, /books?/],
    key: "learning",
    ownPatterns: [
      /\bbooks?\b/,
      /learn/,
      /science/,
      /history/,
      /language/,
      /study/,
      /lecture/,
      /museum/,
      /podcast/,
      /philosophy/,
      /psychology/,
      /debate/,
    ],
    taxonomyIds: ["education", "books_learning"],
  },
  {
    contextPatterns: [/social/, /community/, /values/],
    key: "social",
    ownPatterns: [
      /social/,
      /party/,
      /club/,
      /network/,
      /volunteer/,
      /community/,
      /meetup/,
      /events?/,
      /activism/,
    ],
    taxonomyIds: ["social", "life_values"],
  },
  {
    contextPatterns: [/wellness/, /fitness/, /health/],
    key: "wellness",
    ownPatterns: [
      /wellness/,
      /fitness/,
      /yoga/,
      /\brun\b/,
      /running/,
      /gym/,
      /meditation/,
      /pilates/,
      /mindful/,
      /\bwalk(?:ing)?\b/,
    ],
    taxonomyIds: ["wellness", "fitness_sport", "healthcare"],
  },
];
