"use client";
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from "boneyard-js";
import { configureBoneyard } from "boneyard-js/react";
import _activity_page from "./activity.page.bones.json";
import _auth_activate_page from "./auth.activate-page.bones.json";
import _auth_forgot_password_page from "./auth.forgot-password-page.bones.json";
import _auth_login_page from "./auth.login-page.bones.json";
import _auth_register_page from "./auth.register-page.bones.json";
import _auth_reset_password_page from "./auth.reset-password-page.bones.json";
import _explore_feed from "./explore.feed.bones.json";
import _explore_lens from "./explore.lens.bones.json";
import _explore_page from "./explore.page.bones.json";
import _forge_manual_friends from "./forge.manual-friends.bones.json";
import _forge_page from "./forge.page.bones.json";
import _forge_recent_activity from "./forge.recent-activity.bones.json";
import _forge_template_suggestions from "./forge.template-suggestions.bones.json";
import _home_page from "./home.page.bones.json";
import _landing_page from "./landing.page.bones.json";
import _onboarding_interests_catalog from "./onboarding.interests-catalog.bones.json";
import _onboarding_interests_page from "./onboarding.interests-page.bones.json";
import _onboarding_personality_page from "./onboarding.personality-page.bones.json";
import _onboarding_profile_page from "./onboarding.profile-page.bones.json";
import _profile_page from "./profile.page.bones.json";
import _settings_active_sessions from "./settings.active-sessions.bones.json";
import _settings_blocked_users from "./settings.blocked-users.bones.json";
import _settings_page from "./settings.page.bones.json";
import _settings_preferences from "./settings.preferences.bones.json";

configureBoneyard({
  color: "var(--boneyard-bone-light)",
  darkColor: "var(--boneyard-bone-dark)",
  animate: "pulse",
  shimmerColor: "var(--boneyard-shimmer-light)",
  darkShimmerColor: "var(--boneyard-shimmer-dark)",
  speed: "2.4s",
  shimmerAngle: 110,
  stagger: false,
  transition: false,
  boneClass: "boneyard-bone",
});

registerBones({
  "auth.login-page": _auth_login_page,
  "auth.register-page": _auth_register_page,
  "auth.forgot-password-page": _auth_forgot_password_page,
  "auth.reset-password-page": _auth_reset_password_page,
  "auth.activate-page": _auth_activate_page,
  "activity.page": _activity_page,
  "explore.feed": _explore_feed,
  "explore.lens": _explore_lens,
  "explore.page": _explore_page,
  "forge.manual-friends": _forge_manual_friends,
  "forge.page": _forge_page,
  "forge.recent-activity": _forge_recent_activity,
  "forge.template-suggestions": _forge_template_suggestions,
  "home.page": _home_page,
  "landing.page": _landing_page,
  "onboarding.interests-catalog": _onboarding_interests_catalog,
  "onboarding.interests-page": _onboarding_interests_page,
  "onboarding.personality-page": _onboarding_personality_page,
  "onboarding.profile-page": _onboarding_profile_page,
  "profile.page": _profile_page,
  "settings.active-sessions": _settings_active_sessions,
  "settings.blocked-users": _settings_blocked_users,
  "settings.page": _settings_page,
  "settings.preferences": _settings_preferences,
});
