export type ScenarioFeature =
  | "Activity"
  | "Admin"
  | "Authentication"
  | "Cross-app"
  | "Explore"
  | "Forge"
  | "Groups"
  | "Home"
  | "Network"
  | "Notifications"
  | "Profile"
  | "Safety"
  | "Settings";

export interface ScenarioCatalogEntry {
  description: string;
  feature: ScenarioFeature;
  id: string;
  overlays?: readonly string[];
  persona?: string;
  route: string;
  title: string;
}

export const scenarioCatalog = [
  scenario(
    "standard",
    "Standard account",
    "Cross-app",
    "/home",
    "Coherent authenticated baseline.",
  ),
  scenario(
    "empty",
    "Empty account",
    "Cross-app",
    "/home",
    "Authenticated account with empty product collections.",
    ["empty"],
  ),
  scenario(
    "dense",
    "Dense account",
    "Cross-app",
    "/home",
    "High-volume lists and notifications.",
    ["dense"],
  ),
  scenario(
    "long-copy",
    "Long content",
    "Cross-app",
    "/home",
    "Long names, titles, and descriptions.",
    ["long-copy"],
  ),
  scenario(
    "missing-media",
    "Missing media",
    "Cross-app",
    "/home",
    "All optional images are unavailable.",
    ["missing-media"],
  ),
  scenario(
    "restricted",
    "Restricted account",
    "Cross-app",
    "/home",
    "Restricted visibility and unavailable actions.",
    ["restricted"],
  ),

  scenario(
    "signed-out",
    "Signed out",
    "Authentication",
    "/auth/login",
    "Unauthenticated routing and public surfaces.",
    [],
    "signed-out",
  ),
  scenario(
    "onboarding-incomplete",
    "Onboarding incomplete",
    "Authentication",
    "/onboarding/profile",
    "Profile basics still need to be completed.",
    ["onboarding-incomplete"],
  ),

  scenario(
    "home-standard",
    "Home · mixed",
    "Home",
    "/home",
    "Attention items, upcoming plans, and active groups.",
  ),
  scenario(
    "home-empty",
    "Home · empty",
    "Home",
    "/home",
    "No attention items, plans, or groups.",
    ["empty"],
  ),
  scenario(
    "home-dense",
    "Home · dense",
    "Home",
    "/home",
    "Dense attention and group collections.",
    ["dense"],
  ),
  scenario(
    "home-long-copy",
    "Home · long copy",
    "Home",
    "/home",
    "Stress test for wrapping and truncation.",
    ["long-copy"],
  ),
  scenario(
    "home-loading",
    "Home · loading groups",
    "Home",
    "/home",
    "The group summary remains pending while independent home data resolves.",
  ),
  scenario(
    "home-recommendations-error",
    "Home · recommendations error",
    "Home",
    "/home",
    "The recommendations panel fails while the rest of Home remains available.",
  ),
  scenario(
    "home-recommendations-recovery",
    "Home · recommendations recover",
    "Home",
    "/home",
    "The recommendations panel recovers after an explicit retry.",
  ),

  scenario(
    "activity-standard",
    "Activity · standard",
    "Activity",
    "/activity",
    "Groups and conversations available to the viewer.",
  ),
  scenario(
    "activity-empty",
    "Activity · empty",
    "Activity",
    "/activity",
    "No groups, conversations, or saved messages.",
    ["activity-empty"],
  ),
  scenario(
    "activity-dense",
    "Activity · dense",
    "Activity",
    "/activity",
    "A busy conversation list with many active groups.",
    ["dense"],
  ),
  scenario(
    "activity-long-copy",
    "Activity · long copy",
    "Activity",
    "/activity",
    "Long group names and activity summaries.",
    ["long-copy"],
  ),
  scenario(
    "activity-loading",
    "Activity · loading conversations",
    "Activity",
    "/activity",
    "The activity group collection remains pending.",
  ),

  scenario(
    "notifications-standard",
    "Notifications · mixed",
    "Notifications",
    "/home",
    "Read and unread notifications in the drawer.",
  ),
  scenario(
    "notifications-empty",
    "Notifications · empty",
    "Notifications",
    "/home",
    "The notification drawer has no items.",
    ["notifications-empty"],
  ),
  scenario(
    "notifications-dense",
    "Notifications · dense",
    "Notifications",
    "/home",
    "A long, grouped notification history.",
    ["dense"],
  ),
  scenario(
    "notifications-long-copy",
    "Notifications · long copy",
    "Notifications",
    "/home",
    "Notification titles and descriptions wrap across multiple lines.",
    ["long-copy"],
  ),

  scenario(
    "explore-standard",
    "Explore · mixed",
    "Explore",
    "/explore",
    "A varied local and online result set.",
  ),
  scenario(
    "explore-empty",
    "Explore · filtered empty",
    "Explore",
    "/explore",
    "No results after filtering.",
    ["explore-empty"],
  ),
  scenario(
    "explore-online",
    "Explore · online only",
    "Explore",
    "/explore",
    "Only online opportunities.",
    ["online-only"],
  ),
  scenario(
    "explore-unscheduled",
    "Explore · unscheduled",
    "Explore",
    "/explore",
    "Plans without fixed dates.",
    ["unscheduled"],
  ),
  scenario(
    "explore-full",
    "Explore · full group",
    "Explore",
    "/explore",
    "Groups at their capacity boundary.",
    ["full-groups"],
  ),
  scenario(
    "explore-loading",
    "Explore · initial loading",
    "Explore",
    "/explore",
    "The first page of openings remains pending.",
  ),
  scenario(
    "explore-pagination-loading",
    "Explore · loading more",
    "Explore",
    "/explore",
    "The first page is visible while the next page remains pending.",
    ["pagination"],
  ),
  scenario(
    "explore-join-pending",
    "Explore · joining",
    "Explore",
    "/explore",
    "A join mutation remains pending after the action is selected.",
  ),
  scenario(
    "explore-join-rollback",
    "Explore · join conflict",
    "Explore",
    "/explore",
    "A join mutation conflicts and returns the action to its retryable state.",
  ),

  scenario(
    "forge-standard",
    "Forge · start",
    "Forge",
    "/forge?open=true&step=1",
    "The complete manual Forge flow.",
  ),
  scenario(
    "forge-validation",
    "Forge · validation",
    "Forge",
    "/forge?open=true&step=3",
    "Validation and missing-field states.",
    ["validation"],
  ),
  scenario(
    "forge-long-copy",
    "Forge · long content",
    "Forge",
    "/forge?open=true&step=3",
    "Long plan and group names.",
    ["long-copy"],
  ),
  scenario(
    "forge-no-recent",
    "Forge · no recent items",
    "Forge",
    "/forge?open=true&step=1",
    "No recent templates or activities.",
    ["empty-recent"],
  ),
  scenario(
    "forge-success",
    "Forge · group ready",
    "Forge",
    "/forge?open=true&step=5",
    "Successful group formation with a complete participant roster.",
  ),
  scenario(
    "forge-failed",
    "Forge · no group yet",
    "Forge",
    "/forge?open=true&step=5",
    "Failed group formation with recovery guidance.",
  ),

  scenario(
    "group-member",
    "Group · member",
    "Groups",
    "/groups/scenario-group-basketball",
    "Member view with a confirmed plan.",
  ),
  scenario(
    "group-visitor",
    "Group · visitor",
    "Groups",
    "/groups/scenario-group-invite",
    "Public visitor with an invitation.",
  ),
  scenario(
    "group-admin",
    "Group · admin",
    "Groups",
    "/groups/scenario-group-basketball",
    "Administrative group actions.",
    ["group-admin"],
  ),
  scenario(
    "group-full",
    "Group · full",
    "Groups",
    "/groups/scenario-group-invite",
    "No available member slots.",
    ["full-groups"],
  ),
  scenario(
    "group-no-plan",
    "Group · no plan",
    "Groups",
    "/groups/scenario-group-invite",
    "Active group without a current plan.",
  ),
  scenario(
    "group-draft",
    "Group · draft plan",
    "Groups",
    "/groups/scenario-group-basketball",
    "A plan still being decided.",
    ["draft-plan"],
  ),
  scenario(
    "group-loading",
    "Group · loading details",
    "Groups",
    "/groups/scenario-group-basketball",
    "The group detail request remains pending.",
  ),
  scenario(
    "group-dormant",
    "Group · dormant",
    "Groups",
    "/groups/scenario-group-basketball",
    "A quiet group with explicit resume, transfer, and archive choices.",
    ["group-admin", "dormant-group"],
  ),
  scenario(
    "group-archived",
    "Group · archived",
    "Groups",
    "/groups/scenario-group-basketball",
    "A read-only archived group that its owner can restore.",
    ["group-admin", "group-archived"],
  ),
  scenario(
    "plan-reconfirmation",
    "Plan · reconfirmation",
    "Groups",
    "/groups/scenario-group-basketball",
    "A material plan change has made the viewer's earlier response stale.",
    ["stale-commitment"],
  ),
  scenario(
    "plan-waitlist",
    "Plan · waitlisted",
    "Groups",
    "/groups/scenario-group-basketball",
    "The viewer is waiting for a recoverable plan place.",
    ["seat-waitlisted"],
  ),
  scenario(
    "plan-seat-offer",
    "Plan · place offered",
    "Groups",
    "/groups/scenario-group-basketball",
    "A time-limited place is ready for the viewer to accept or decline.",
    ["seat-offered"],
  ),
  scenario(
    "group-ownership-pending",
    "Group · ownership pending",
    "Groups",
    "/groups/scenario-group-basketball",
    "A named ownership recipient still needs to respond.",
    ["group-admin", "ownership-pending"],
  ),
  scenario(
    "group-guest-promotion",
    "Group · guest promotion",
    "Groups",
    "/groups/scenario-group-basketball",
    "An attending guest is waiting for member consensus.",
    ["group-admin", "guest-promotion-pending"],
  ),
  scenario(
    "plan-guest",
    "Plan · guest",
    "Groups",
    "/plans/scenario-plan-basketball/guest",
    "A guest place with intentionally limited access to the group.",
    ["plan-guest"],
  ),
  scenario(
    "external-invite",
    "Plan · external invitation",
    "Groups",
    "/invite",
    "A privacy-limited preview for a single-use plan invitation.",
    ["plan-guest"],
  ),

  scenario(
    "profile-owner",
    "Profile · owner",
    "Profile",
    "/profile",
    "Full profile and personality data.",
  ),
  scenario(
    "profile-public",
    "Profile · public",
    "Profile",
    "/users/scenario-user-ava",
    "Another member's public profile.",
  ),
  scenario(
    "profile-private",
    "Profile · private",
    "Profile",
    "/users/scenario-user-ava",
    "Private optional profile fields.",
    ["private-profile"],
  ),
  scenario(
    "profile-no-assessment",
    "Profile · no assessment",
    "Profile",
    "/profile",
    "Profile without personality results.",
    ["no-assessment"],
  ),
  scenario(
    "profile-loading",
    "Profile · loading",
    "Profile",
    "/users/scenario-user-ava",
    "The public profile request remains pending.",
  ),

  scenario(
    "settings-standard",
    "Settings · standard",
    "Settings",
    "/settings",
    "Default account settings.",
  ),
  scenario(
    "settings-export-waiting",
    "Settings · export waiting",
    "Settings",
    "/settings?section=privacy",
    "Account export is being prepared.",
    ["export-waiting"],
  ),
  scenario(
    "settings-many-sessions",
    "Settings · many sessions",
    "Settings",
    "/settings?section=security",
    "Many active sessions and devices.",
    ["many-sessions"],
  ),
  scenario(
    "settings-loading",
    "Settings · loading preferences",
    "Settings",
    "/settings?section=notifications",
    "Profile settings remain usable while notification preferences are pending.",
  ),
  scenario(
    "settings-notification-timing",
    "Settings · notification timing",
    "Settings",
    "/settings?section=notifications",
    "Reminder timing, quiet hours, and delivery controls.",
  ),
  scenario(
    "settings-presence-hidden",
    "Settings · presence hidden",
    "Settings",
    "/settings?section=privacy",
    "The most private last-seen precision is selected.",
    ["presence-hidden"],
  ),
  scenario(
    "settings-presence-exact",
    "Settings · exact presence",
    "Settings",
    "/settings?section=privacy",
    "Exact last-seen detail shared with every supported audience.",
    ["presence-exact"],
  ),

  scenario(
    "safety-active",
    "Safety · active records",
    "Safety",
    "/safety",
    "Reports, account actions, and temporary restrictions.",
  ),
  scenario(
    "safety-empty",
    "Safety · empty",
    "Safety",
    "/safety",
    "No reports, account actions, or restrictions.",
    ["safety-empty"],
  ),

  scenario(
    "admin-standard",
    "Admin · standard",
    "Admin",
    "/admin",
    "Admin surface with recent verification.",
    [],
    "admin",
  ),
  scenario(
    "admin-stale-verification",
    "Admin · stale verification",
    "Admin",
    "/admin",
    "Admin controls require step-up verification.",
    ["stale-verification"],
    "admin",
  ),
  scenario(
    "admin-empty-queues",
    "Admin · empty queues",
    "Admin",
    "/admin/moderation",
    "No cases or reports waiting.",
    ["admin-empty"],
    "admin",
  ),
  scenario(
    "admin-worker-degraded",
    "Admin · degraded worker",
    "Admin",
    "/admin/moderation/workers",
    "Worker health and retry boundaries.",
    ["worker-degraded"],
    "admin",
  ),

  scenario(
    "network-slow",
    "Slow network",
    "Network",
    "/home",
    "All handled requests wait two seconds.",
    ["network-slow"],
  ),
  scenario(
    "network-offline",
    "Offline",
    "Network",
    "/home",
    "All API requests fail without contacting the backend.",
    ["network-offline"],
  ),
  ...([403, 404, 409, 410, 422, 429, 500] as const).map((status) =>
    scenario(
      `network-${status}`,
      `HTTP ${status}`,
      "Network",
      "/home",
      `All API requests return HTTP ${status}.`,
      [`network-${status}`],
    ),
  ),
] as const satisfies readonly ScenarioCatalogEntry[];

export function getScenarioCatalogEntry(id: string) {
  return scenarioCatalog.find((entry) => entry.id === id) ?? null;
}

function scenario(
  id: string,
  title: string,
  feature: ScenarioFeature,
  route: string,
  description: string,
  overlays: readonly string[] = [],
  persona?: string,
): ScenarioCatalogEntry {
  return { description, feature, id, overlays, persona, route, title };
}
